### ISSUE TITLE
Publish to GitHub pages

### ISSUE THREAD

**Issue by gbraad** [jtpio/jupyterlite#114]
### Problem

Lowering the entry barrier

### Proposed Solution

Allow `_static` to be published to GitHub Pages

**Comment by jtpio** [comment]
Thanks @gbraad.

This is indeed one of the many deployments scenarios that will eventually be documented in https://jupyterlite.readthedocs.io/en/latest/deploying.html#github-pages

Currently tracked in https://github.com/jtpio/jupyterlite/issues/67.

Once there is proper tooling (at least published as a `jupyterlite` Python package, https://github.com/jtpio/jupyterlite/issues/41#issuecomment-834622806) it should become much easier for anyone to deploy their own JupyterLite to all these different providers.

**Comment by gbraad** [comment]
Would you want me to close this issue in favor of the more generic documentation task?

However, I believe the situation for GitHub can be automated as a process with GitHub Actions.

**Comment by jtpio** [comment]
> Would you want me to close this issue in favor of the more generic documentation task?

Let's consolidate the discussion in https://github.com/jtpio/jupyterlite/issues/67?

With this current issue, were you referring to the deployment of the demo site (currently on Read The Docs), to also be published to GitHub Pages? Or were you thinking about the deployment case by end users? (https://jupyterlite.readthedocs.io/en/latest/deploying.html#github-pages)

> However, I believe the situation for GitHub can be automated as a process with GitHub Actions.

Absolutely. The reason the demo site is deployed to RTD for now is because PRs can have preview links: https://jupyterlite.readthedocs.io/en/latest/contributing.html#previews

If you would like to contribute to the docs for deploying to GitHub Pages, that would be very appreciated. Thanks!

**Comment by bollwyvl** [comment]
This may well warrant a separate discussion than the others, as it will have more long-term effects (e.g. every `git fetch` will bring it in). But I concur with @jtpio, we should invest more effort on making proper CLI/in-Lab GUI tooling that we can distribute through _normal means_, as the extend-by-fork is... brittle. Maybe i'll start throwing stuff at the wall...

From a docs perspective, gh-pages still makes a _ton_ of sense, though, and that discussion very much belongs on #67.

I feel like if we do offer this on _this_ repo's github pages, it should be as minimal as possible, and not carry all of the extra extensions and examples we're adding to the docs site, if only so the churn is slightly reduced, and reduce the amount of hacking downstreams would want to do... it should be possible to just _copy_ files, rather than _patch_ files. At any rate, we'll probably want to hold off anyway until we get deduplication of the the main build assets between `lab/` and `retro/`.

**Comment by jtpio** [comment]
> (e.g. every git fetch will bring it in)

Yes that was also a reason for not having for this repo, but there could definitely be a separate demo repo that would deploy to GitHub pages.

> At any rate, we'll probably want to hold off anyway until we get deduplication of the the main build assets between lab/ and retro/.

Probably something that belongs to #41, but I guess we can already start packaging the app (with the deduplicated assets) and publish to PyPI. To start getting the releases out. Folks who want to deploy to GitHub Actions could then `pip install jupyterlite` and then copy the static assets (could be from `PREFIX/share/jupyter/lite/static` or similar)

**Comment by jtpio** [comment]
An example repo deploying JupyterLite to GitHub Pages: https://github.com/jtpio/jupyterlite-demo

For now it downloads the tarball from a GitHub Release: https://github.com/jtpio/jupyterlite-demo/blob/f26c6dfae87dcb3946fe98d2e7053af5f9a90e8f/.github/workflows/deploy.yml#L19

And the rest is mostly about copying files around. As mentioned above this should be made more convenient with better tooling.
