### ISSUE TITLE
Default list of federated extensions on the demo website

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#83]
Follow-up to #58 

To showcase the use of existing federated extensions for JupyterLab (and JupyterLab Classic):

- `ipydrawio`
- `jupyterlab-cell-flash`
- `jupyterlab-tour`: #31 
- cool themes
- ?

This is to fix the following TODO:

https://github.com/jtpio/jupyterlite/blob/373b8aaeb4b92e9fc7697d2bedd51c5125c14457/docs/conf.py#L97-L99

**Comment by bollwyvl** [comment]
Thanks for repping those first ones... Kinda torn as we want something in
there quick, but really want to start moving towards the "real deal"
tooling.

As mentioned, I move that we put darcula in that way instead of compiled in.

Some more wins for (maybe) docs:

- jupyterlab-videochat
  - needs some decoupling from serverextension, working on it
  - might need settings overrides
  - ain't gonna work in classic, yet, though
- jupyterlab-markup
  - though we kinda need the myst stuff to really hit it out of the park
- some of the jupyterlab-renderers
  - just because

Of course, the mime ones won't be fun until we can ship contents.

**Comment by jtpio** [comment]
>   - ain't gonna work in classic, yet, though

I think it's totally fine if they don't all work in classic. It would already be really impressive to have it in lab.

> - some of the jupyterlab-renderers - just because

Those will be useful so we can double check loading mime extensions as federated works as expected.

**Comment by bollwyvl** [comment]
Yep, perhaps for stuff we _know_ doesn't work with classic we can start it
just in /lab/jupyterlite.json... just makes the docs:extensions slightly
more complicated.

I think any optional goodies that don't make the site _too_ much slower to
load initially is good.

Part of this is on extension developers, for sure, but we should make sure
first party lite stuff is as lazy / non-blocking as possible.

For example, a servlitextension needs to register its routes, but doesn't
actually need to load its deps until a request actually comes in... Though
it could schedule a prefetch.

Similarly, the hard preload of matplotlib/numpy is kinda crushing to
time-to-execute-reply...

**Comment by bollwyvl** [comment]
I think with `disabledExtensions` in, we are doing this pretty well.

**Comment by jtpio** [comment]
Yes, and we can add more extensions to the demo site later if we want to.
